export { IconWrapper } from './IconWrapper';

export { Close, Close as CloseIcon } from './Close';
export { Check, Check as CheckIcon } from './Check';
export { Upload, Upload as UploadIcon } from './Upload';
export { Eye, Eye as EyeIcon } from './Eye';
export { EyeOff, EyeOff as EyeOffIcon } from './EyeOff';
export { Info, Info as InfoIcon } from './Info';
export { Success, Success as SuccessIcon } from './Success';
export { Warning, Warning as WarningIcon } from './Warning';
export { TriangleDown, TriangleDown as TriangleDownIcon } from './TriangleDown';
export { ChevronUp, ChevronUp as ChevronUpIcon } from './ChevronUp';
export { ChevronLeft, ChevronLeft as ChevronLeftIcon } from './ChevronLeft';
export { ChevronDown, ChevronDown as ChevronDownIcon } from './ChevronDown';
export { Indeterminate, Indeterminate as IndeterminateIcon } from './Indeterminate';
export { Image, Image as ImageIcon } from './Image';
export { Pdf, Pdf as PdfIcon } from './Pdf';
export { Document, Document as DocumentIcon } from './Document';
export { Spreadsheet, Spreadsheet as SpreadsheetIcon } from './Spreadsheet';
export { Archive, Archive as ArchiveIcon } from './Archive';
export { Audio, Audio as AudioIcon } from './Audio';
export { Video, Video as VideoIcon } from './Video';
export { File, File as FileIcon } from './File';
export { Burger, Burger as BurgerIcon } from './Burger';
export { Dot, Dot as DotIcon } from './Dot';
